pipeline{
    agent none
    stages{
        agent {
            dockerfile {
                dir 'passwordmanager'
            }
        }
        stage {
            echo 'testando docker'
        }
        
    }
}