pipeline{
    agent none
    stages{
        stage('Build') {
            agent {
                dockerfile {
                    dir 'passwordmanager'
                }
            }
            steps {
                echo 'bild docker'
            }
        }
    }
}